# Configuration Settings for C94-M8P device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

save:
  mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver 
                            # Manager, Antenna, and Logging Configuration
  device: 4                 # Save to EEPROM

device: /dev/ttyUSB0
frame_id: m8n 
dynamic_model: 5    # Airborne < 2G, 2D fix not supported (3D only), 
                            # Max Alt: 50km
                            # Max Horizontal Velocity: 250 m/s, 
                            # Max Vertical Velocity: 100 m/s
enable_ppp: false           # Not supported by C94-M8P
dr_limit: 1

gnss:
  glonass: true             # Supported by C94-M8P
  beidou: false             # Supported by C94-M8P
  qzss: false               # Supported by C94-M8P

dgnss_mode: 3               # Fixed mode

inf: 
  all: true                   # Whether to display all INF messages in console

# Enable u-blox message publishers
publish:
  all: true
  esf: true
  aid:
    hui: false
  nav:
    posecef: false
